print ("*~-~_Welcome to your Journey Brave Traveler_~-~*")
UserName = input(f"By what \033[32mname\033[0m shall we call you?:")
print (f"Of course", "\033[32m", UserName, "\033[0m", "the great", "\033[36m", "We've been expecting you...", "\033[0m")
Weapon = input(f"...You now have a choice \033[32m{UserName}\033[0m what is one item you will take with you on this unknown journey?: ")
print()
print(f"Ah yes, the", "\033[32m", Weapon, "\033[0m", "it is, a fine choice")
print()
print("Now\033[36m we stare into the orb of chance and ponder your next decision\033[0m")
Fear = input(f"What is your greatest fear?:")
print(f"Ah yes, the", "\033[32m", Fear, "\033[0m" "it is, a terrible fear")
print()
print(f"\033[36mBUT YOU ARE GREATER\033[0m")
print()
print(f"The orb speaks to you", "\033[32m", UserName, "\033[0m")
print()
print(f"\033[35m{UserName} You are much greater than{Fear}and you will be able to defeat it with your{Weapon}")

